version: "3"

services:
  api:
    image: "chrisns/docker-node-sonos-http-api"
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/api/settings.json:/app/settings.json
  controller:
    image: "stepman0/sonos-kids-controller"
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/controller/config:/sonos-kids-controller/server/config/
      - ./data/controller/logs:/home/node/.npm/_logs/
